### ISSUE TITLE
Spring Security 

### ISSUE THREAD

**Issue by GabrielLimaBzr** [gilmaresende/cursos-java#1]
Conseguiu liberar o h2 ? estou tendo problema com auteticação recebo direto forbidden 403

**Comment by gilmaresende** [comment]
Cara, os erros de depreciação consegui corrigir com os videos deste cara
https://www.youtube.com/watch?v=laaCEkhf5cU&list=PLXjt2Adje6u7WSsf1oc99zRsbF9-d-qnE&index=2&ab_channel=RodrigoFreitas
na epoca que eu tava fazendo ele ainda não tinha soltado todas as aulas. Eu ainda tenho de terminar de adaptar ao curso do Valdir, então não tenho certeza se vai liberar o H2

**Comment by GabrielLimaBzr** [comment]
entendi, essa depreciação me quebrou muito, vou estudar mais o security
